version: "3.9"
services:
  ### Database ###
  postgres:
    image: postgres:14.1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
### API Spring Boot ###
  api:
    build:
      dockerfile: Dockerfile
      context: ./
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:5432/postgres
      DATABASE_USER: user
      DATABASE_PASSWORD: password
    ports:
      - "8080:8080"
